# Generated by Django 4.1.3 on 2023-02-17 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book.', max_length=70)),
                ('am_link', models.URLField(verbose_name='Amazon Link')),
                ('notes', models.TextField(blank=True, help_text='Notes for the book.', null=True)),
                ('book_started', models.BooleanField(default=False, verbose_name='Book Started?')),
                ('book_finished', models.BooleanField(default=False, verbose_name='Book Finished?')),
                ('max_pg_num', models.PositiveIntegerField(blank=True, verbose_name='The page length of the book.')),
                ('isbn', models.CharField(blank=True, help_text='The ISBN number of the book.', max_length=20)),
                ('date_started', models.DateTimeField(blank=True, null=True, verbose_name='Date the book was started.')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('book_finished',),
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(help_text="The contributor's first name or names.", max_length=50)),
                ('last_names', models.CharField(help_text="The contributor's last name or names.", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='The rating for the book.', validators=[django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(help_text='The Review text.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time the review was created.')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role this contributor had in the book.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contributor')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='core.BookContributor', to='core.contributor'),
        ),
    ]
